### ISSUE TITLE
Options aren't found if <argument> is too long

### ISSUE THREAD

**Issue by alexchandel** [docopt/docopt.hs#16] opened 2015-06-29 16:19 UTC
Consider the usage text:
```
Usage:
  foo <argument>
  foo --help

Options:
  -h, --help        Print this message.
  -v, --verbose     Print extra warnings and information.
```

When invoked as `foo --help` or as `foo -h`, `(isPresent args (longOption "help"))` will return false. This is unsettling.

**Comment by alexchandel** [comment] 2015-06-29 16:22
The important thing to note is that if `<argument>` is shortened to `<bar>`, this doesn't not misbehave.

**Comment by ryanartecona** [comment] 2015-07-05 15:22
I will try to reproduce this to be safe, but at face value this looks like the same issue I just described in my response to #17. Are you sure you hit this issue by changing nothing but `<argument>` to `<bar>`?

**Comment by ryanartecona** [comment] 2015-11-08 04:20
I was able to reproduce this, and have a fix incoming which will be in the next release.

**Closed** 2015-11-08 04:33 UTC
